
name: deploy wps-landing
on: 
  push:
    branches:
      - develop
env: 
  PORT: ${{secrets.PORT}}
  REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL}}
jobs:
  deploy:
    name: Build Frontend wps-landing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build and push to docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: tekstudiodev/${{ github.repository }}