
name: deploy wps-landing
on: 
  push:
    branches:
      - develop
jobs:
  build_front:
    name: Build Frontend wps-landing
    runs-on: ubuntu-latest
    uses: actions/checkout@master
    steps:
      - name: Checkout repository
        run: | 
          touch wps-environment
          echo "export PORT=${secrets.PORT}" >> wps-environment
          echo "export REACT_APP_API_URL=${secrets.REACT_APP_API_URL}" >> wps-environment
          cat wps-environment
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        path: |
          wps-environment
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: wps-environment
      - uses: actions/checkout@master
      - name: build and push to docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: tekstudiodev/${{ github.repository }}