
name: deploy wps-landing
on: 
  push:
    branches:
      - develop
env: 
  PORT: ${{secrets.PORT}}
  REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL}}
jobs:
  deploy:
    name: Build Frontend wps-landing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build and push to docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: tekstudiodev/wps-landing
          tag_with_ref: true
          tag_with_sha: true
          tags: latest
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
            
      - name: deploy server
        run: sh bin/deploy.sh
        env: 
          VERSION: latest
          CONTAINER_NAME: tekstudiodev/wps-landing
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST}}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER}}
          DOCKER_COMPOSE_FILE: ${{ secrets.DOCKER_COMPOSE_FILE}}
